### ISSUE TITLE
Tokenizer

### ISSUE THREAD

**Issue by griff4692** [cambridgeltl/sapbert#2]
Is there any information on the tokenizer from HuggingFace?

`tokenizer = AutoTokenizer.from_pretrained("cambridgeltl/SapBERT-from-PubMedBERT-fulltext")`

I assume it's the same as PubmedBERT, which I presume is using an 'in-domain' vocabulary.  Just would love confirmation!   thanks

**Comment by hardyqr** [comment]
Hi, yes you are right. It is the same vocab as PubMedBERT as cambridgeltl/SapBERT-from-PubMedBERT-fulltext is initialised from the PubMedBERT checkpoint :)
