### ISSUE TITLE
MedMentions Dictionary file created

### ISSUE THREAD

**Issue by saranyakrishm** [cambridgeltl/sapbert#3]
Hello Team
Thank you for your great contribution. Can you please brief me on how was the medmentions dictionary file was created to run evaluations.

Thanks
Saranya

**Comment by hardyqr** [comment]
Hi Saranya, thanks for your interest in our work! 
We downloaded UMLS2017AA's MRCONSO file and extracted the CUI-name pairs in the following form:
```
C0079564||htlv-ii rex protein
C0162999||oleoylamine
C0347197||benign mouth neoplasm
...
```
In the end, there should be around 7.4M individual lines (after deleting duplicated lines) and around 3.4M individual concepts (CUIs) in the dictionary file. Hope this helps!

Best,
Fangyu
