### ISSUE TITLE
dictionary for custom dataset

### ISSUE THREAD

**Issue by NargesFarrokhshad** [cambridgeltl/sapbert#5]
Hello and thank you for sharing this project.

I want to evaluate this model on my custom dataset. How can I create a dictionary for that?

**Comment by hardyqr** [comment]
Hi, apologies for the delayed response. Would you like to fine-tune then test or directly test?

If you'd like to test directly, then you can follow the dataset format here: https://github.com/cambridgeltl/sapbert/tree/main/evaluation (also some available datasets for download)

If you'd like to fine-tune then test, you can refer to my response to this issue: https://github.com/cambridgeltl/sapbert/issues/4
