### ISSUE TITLE
mention detection (how to?)

### ISSUE THREAD

**Issue by runfish5** [cambridgeltl/sapbert#8]
Hi SapBERT authors, this code is so valuable!

With this code, I can link biomedical entities to the UMLS entities. In my case, I want to give a sentence-query, like needed for the evaluations of the unsupervised trained model. I wonder how the mention detection was performed (not described in paper)?

**Comment by hardyqr** [comment]
Hey, we assume that mention detection was already done and SapBERT only handles the entity normalisation part. If you'd like to input a full sentence then first another entity detection is needed to identify the entities.

**Comment by runfish5** [comment]
Thanks for the fast and concise answer! I already thought it could be like that.

**Comment by runfish5** [comment]
Just a follow up question: What mention-detection tool would you recommend?

I found that sciSpacy reports F1 as follows:
| Model                 | Mentions (F1) |
|-----------------------|---------------|
| `en_core_sci_sm`      | 68.00         |
| `en_core_sci_md`      | 68.95         |
| `en_core_sci_lg`      | 68.67         |
| `en_core_sci_scibert` | 67.90         |
from [this ](https://allenai.github.io/scispacy/)reference.


**I was surprised these scores are so low, so I tested two sentences:**
1) "The Calvin–Benson–Bassham (CBB) cycle is presumably evolved for optimal synthesis of C3 sugars, but not for the production of C2 metabolite acetyl-CoA. The carbon loss in producing acetyl-CoA from decarboxylation of C3 sugar limits the maximum carbon yield of photosynthesis."
    - it missed 1: "maximum carbon yield"
    - The bigger problem is that "Calvin-Benson-Bassham (CBB)" pathway was recognized as three different entities
2) "Here we design a synthetic malyl-CoA-glycerate (MCG) pathway to augment the CBB cycle for efficient acetyl-CoA synthesis."
    -  Missed "pathway", here is the output: "(synthetic malyl-CoA-glycerate, MCG, CBB cycle, acetyl-CoA synthesis)"
  


**Llama**
Next, I considered "meta-llama/Llama-2-7b-hf", put it always produced text unrelated to the instructions.
Next I considered "meta-llama/Llama-2-7b-chat-hf"  , which gave me:
1. Calvin
2. Benson
3. Bassham (CBB)
4. carbon
5. CoA
6. decarboxylation
7. C3
8. sugar
9. photosynthesis



# Conclusion
So I'm still interested in the question of the first sentence: Do you have a recommenation for mention-detection ?
